# Generated by Django 4.0 on 2026-04-07 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='emotion',
            field=models.CharField(choices=[('MUITO_FELIZ', 'Muito Feliz'), ('FELIZ', 'Feliz'), ('NEUTRO', 'Neutro'), ('TRISTE', 'Triste'), ('MUITO_TRISTE', 'Muito Triste'), ('CANSADO', 'Cansado'), ('ANSIOSO', 'Ansioso'), ('ALIVIADO', 'Aliviado')], default='NEUTRO', max_length=20),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='intensity_level',
            field=models.IntegerField(help_text='Escala de 1 a 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
