# Generated by Django 4.0 on 2026-05-28 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_moodentry_emotion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='intensity_level',
            field=models.IntegerField(help_text='Escala de 1 a 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
