CREATE TABLE IF NOT EXISTS "core_moodentry" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" timestamp with time zone NOT NULL,
    "intensity_level" integer NOT NULL,
    "emotion" varchar(20) NOT NULL DEFAULT 'NEUTRO',
    "notes" text NULL,
    "user_id" integer NOT NULL,
    CONSTRAINT "core_moodentry_user_id_fk"
        FOREIGN KEY ("user_id")
        REFERENCES "auth_user" ("id")
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "core_moodentry_user_id_idx"
    ON "core_moodentry" ("user_id");

CREATE INDEX IF NOT EXISTS "core_moodentry_created_at_idx"
    ON "core_moodentry" ("created_at" DESC);
